# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Nico/Documents/Projects/Firmware/FPGA_LAB4/pinout.xdc

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Nico/Documents/Projects/Firmware/FPGA_LAB4/FPGA_LAB4.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
